### ISSUE TITLE
How much strain is put on networks (e.g. WIFI) when sending data to many clients via WebSockets simultaneously

### ISSUE THREAD

**Issue by viruslight** [wildyeast/sadiss#55]
How many clients can a given WIFI network handle at the same time?
What does this depend on?
Can we tell beforehand, without testing?
Would it be easier on the network if we spread out the sending of data over the full second we have got available?

**Comment by wildyeast** [comment]
Household routers have a maximum number of devices that can be connected. That number is usually 16 or 32 (for example TL-MR6400), but no more than 256. This means that unless a venue has a dedicated wifi system for exactly our kind of applications, we are limited to a very low number of clients.

I've just measured the output of SADISS server with a few of Volkmar's current tracks with a maximum 1.47 Mbit/s (average 525 kbit/s). I only used one device for testing, but I think that there is a lot of headroom before we reach the limit of a common household router, which is 300 Mbit/s. During the next performance I will monitor the bandwidth in real-time for us to do some realistic estimates.

**Comment by wildyeast** [comment]
During yesterday's performance with a maximum of 37 connected clients we collected the following data:

receiving: 113 kbit/s max.
transmitting: 4 Mbit/s max.

We can therefore assume that the SADISS server transmits around 11 Mbit/s per 100 clients. We can use this number for calculating the potential load on a performance WIFI network.

On our current server (Hetzner cloud VM) we have a dedicated 1 GBit uplink. Based on the calculations above, this server can support no more than 9k clients. I suggest that we look into providers that offer a higher bandwidth (Hetzner does not).
