### ISSUE TITLE
Uploading tracks

### ISSUE THREAD

**Issue by KlienVo** [wildyeast/sadiss#63]
After uploading a track it seems to be necessary to reload the admin page to upload the next track. (otherwise the 'new track' pane displays the previous track-name and still says 'uploading'

**Comment by KlienVo** [comment]
Also, in the track editing pane (after clicking on the pencil) there does not seem to be a 'save' button to click. (it only says 'uploading', where one might suspect the save button to be)

**Comment by wildyeast** [comment]
fixed
