### ISSUE TITLE
Server reports wrong no of connected clients

### ISSUE THREAD

**Issue by KlienVo** [wildyeast/sadiss#73]
The admin interface just reported 3 connected devices while acutally 7 phones were connected and playing back. 
(6 of the phones hat been connected overnight already, might that be part of an explanation?)

<img width="347" alt="Screen Shot 2023-04-11 at 18 47 46" src="https://user-images.githubusercontent.com/110396146/231234286-39edc880-143e-4e2a-aa78-c72a87faef3e.png">

**Comment by KlienVo** [comment]
in case it helps:
This was at 2023-04-11 at 18 47 46

**Comment by wildyeast** [comment]
The admin interface monitors connections as soon as it is started, but it forgets this information as soon as its session is terminated. Meaning that if connections are made before the admin interface is loaded in the browser, they will not show up in the counter. A page reload will also reset the counter.

Would be a nice improvement to get the number of connected devices on page load.

**Comment by viruslight** [comment]
Created a new issue for this, see #78. Closing.
