### ISSUE TITLE
Audio Pulsing/Dropout for larger files (andOr bad network connection?)

### ISSUE THREAD

**Issue by KlienVo** [wildyeast/sadiss#82]
The following three Sadiss tracks:
Plantery Skins Anfang
Planetary Skins Anfang Stretched (2x)
Planetary Skins Anfang stretched

based on the following partials/frames files (attached as .zip):
03_UmfassenUmfangen_Stereo_beginning_frames.txt
03_UmfassenUmfangen_Stereo_beginning_Stretched2_frames.txt
03_UmfassenUmfangen_Stereo_beginningStretched_frames.txt
[frames-files.zip](https://github.com/wildyeast/sadiss/files/11895533/frames-files.zip)

The 3 tracks have got the same number of partials. (hence the load of concurrent oscillators run by each client should stay the same for each track)
The tracks only differ in duration (i.e. have been stretched in Spear) and file size.

The two stretched tracks display the audio 1s pulsing error in varying dimensions.
Seems like the 1s buffer download rhythm becomes audible due to some error. (either timing or bandwidth [or whatever] related)

**Comment by KlienVo** [comment]
Many thanks.
In Athens we had the situation that some of the phones had audio signals, others didn't. Am I mistaken oder would this then be caused by something different?

**Comment by viruslight** [comment]
This is quite difficult to say, without reproducing the issue. Track ParkChoir_EN_GR_2023-06-09 and 2x stretched have similar loading times, LenasDoor_EN-GR_2023-06-09 about half of that. So it could very well be that this was, at least in part, the cause of what you observed there.

**Comment by viruslight** [comment]
@KlienVo This should now be fixed, please test and close this issue if it is.

**Comment by viruslight** [comment]
The track data is now read from the file where it is stored as soon as the performer clicks the track in the list of tracks in the performance. While it is loading the track cannot be started, indicated by a clock icon where the play/stop button usually is. Auto-play still works as before.

**Comment by KlienVo** [comment]
Sounds all good now!
Looks like the problem has been solved.
I generated 2 tracks with even bigger file sizes and partial counts now that seem to play back without problem.
1.
PlanetarySkins_Anfang_50MbVersion (partials-count 11761, frame-count 56570)
2.
PlanetarySkins_207Mb (partials-count 11761, frame-count 226277)
