### ISSUE TITLE
Skipping line 1 of SRT

### ISSUE THREAD

**Issue by KlienVo** [wildyeast/sadiss#86]
Birds_Athens_2023-06-09 (now also to be found in performance ‚TestingSite_max16Ids‘)
drops 1st line of ID 8

The srt starts with:
1
00:00:00,867 --> 00:00:09,376
Now we have a favor to ask: When you hear “action”, do the action. .....  When you hear “Say out loud”, say the line.

**Comment by viruslight** [comment]
In the originally uploaded SRT file for voice 8 en-US (see attached txt file), the first line is empty. Could this be the reason, or did we somehow lose this during the upload?

[issue_86_voice8_enUS_origfile.txt](https://github.com/wildyeast/sadiss/files/11999154/issue_86_voice8_enUS_origfile.txt)
